language: scala

dist: xenial

scala:
  - 2.12.8

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_install:
  - sudo apt-get install -y sdpa

script: sbt ++$TRAVIS_SCALA_VERSION tests/test
